### ISSUE TITLE
OID naming

### ISSUE THREAD

**Issue by ornago** [friedlik/web2com#1]
Thank you very much for the help to get values from Web2Com. As long as I am waiting for my ebus-adapter, I'm using your flow in a node-red within Home-Assistant. After looking for all the values i want to have, i created a bunch of flows to request it.
Did you found a way to get a naming of one OID? I get only the first part like "02:51" while seeing "02:51 Status Heizkreis" in the webview.

**Comment by friedlik** [comment]
Dear Mathias, I do not understand what you mean.
Do you mean having a single node to communicate?
I control the hot water production dependent on the solar energy production and the state of the battery charge.
I use two separate "web2com request" request.
 
![Screenshot 2022-11-11 121122](https://user-images.githubusercontent.com/29403399/201328730-2a5c3084-0a04-42ef-89f5-12d7c58a422d.jpg)

**Comment by ornago** [comment]
![image](https://user-images.githubusercontent.com/12096794/201397631-df7f2a0b-ddda-45f5-9006-05d8037b4acf.png)
Thanks for the response, I'll try to explain it better. In the screenshot you could see the webview of my web2com.
On the right side there is:
```
ID 00:00
Name Aussentemperatur
Wert 11.4 °C
```
But in the object getting over SOAP XML is not the name. The 'name' is now the 'ID' from webview.
![image](https://user-images.githubusercontent.com/12096794/201399004-d8c61bf7-4f76-4907-bc80-6ef396b818eb.png)
Maybe it is different in your version of web2com? Not a big problem but would be nice to get the names.

Do you know if it is possible to connect two heat pumps to one Web2Com device? Thanks again for your help in advance.

**Comment by friedlik** [comment]
Dear Mathias, the name is available under object->ref->object-->oid (see below)
![Screenshot 2022-11-11 121122](https://user-images.githubusercontent.com/29403399/201467142-47088c10-608f-4925-a415-b07c35904913.jpg)

**Comment by ornago** [comment]
Yeah, I saw that in your flow. I was hoping to get the real name of this entity, like "Aussentemperatur" in my example.

Can you answer my other question in the last post? Multiple heat pumps on one Web2Com.
We have one "OCHSNER AIR 211 C Basic (ELW8)" and "OCHSNER GMDW 18 Plus". I would like to control the last one and informations from both. We bought a solar battery for our photovoltaik power plant and like to control the heat pump to use more solar energy. Do you have any informations on controlling the GMDW 18 like that?

**Comment by friedlik** [comment]
Dear Matthias, 
I do not have any experience in controlling more than one heat pump with web2com.
But I think it must be possible if both heat pumps are connected to the same eBus having different/unique device ID's.
Best regards,
Kurt

**Comment by ornago** [comment]
Got in contact with OCHSNER about two machines on one Web2Com device. Turns out it’s not possible except for cascades of heat pumps. Thanks for your help
